"""Physio / physician export.

You have a doctor's appointment about the ankle and the knee. Walking in with a
dated symptom log and the training load that produced it is worth more than
twenty minutes of trying to remember. `agoge physio --since 2026-07-01`
"""
from __future__ import annotations

from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path

from .config import Athlete, settings
from .db import DB


def physio_report(db: DB, athlete: Athlete, since: date, until: date | None = None) -> str:
    until = until or date.today()
    s, u = since.isoformat(), until.isoformat()
    out = [
        f"# Training and symptom summary — {athlete.name}",
        f"\nPeriod: {s} to {u}  ({(until - since).days} days)",
        f"\nContext: training for {athlete.raw['race']['name']}, "
        f"{athlete.race_date}. Currently in the "
        f"{(athlete.current_block(until) or {}).get('name', 'unscheduled')} block.",
        "\n## Known history\n",
    ]
    for inj in athlete.injuries:
        out.append(f"- **{inj['label']}** — {inj['rule'].strip()}")

    out.append("\n## Training load\n")
    sessions = db.sessions_between(s, u)
    by_sport: dict[str, list] = defaultdict(list)
    for r in sessions:
        by_sport[r["sport"]].append(r)
    out.append("| Discipline | Sessions | Total min | Total mi | Longest |")
    out.append("|---|---|---|---|---|")
    for sport, rows in sorted(by_sport.items()):
        mins = sum(r["duration_min"] or 0 for r in rows)
        miles = sum(r["distance_mi"] or 0 for r in rows)
        longest = max((r["duration_min"] or 0 for r in rows), default=0)
        out.append(f"| {sport} | {len(rows)} | {mins:.0f} | {miles:.1f} | {longest:.0f} min |")

    out.append("\n### Weekly volume\n")
    weeks: dict[str, float] = defaultdict(float)
    for r in sessions:
        d = date.fromisoformat(r["day"])
        weeks[(d - timedelta(days=d.weekday())).isoformat()] += r["duration_min"] or 0
    out.append("| Week starting | Minutes |")
    out.append("|---|---|")
    for wk in sorted(weeks):
        out.append(f"| {wk} | {weeks[wk]:.0f} |")

    out.append("\n## Symptom log\n")
    syms = db.recent_symptoms(s)
    if not syms:
        out.append("No symptoms recorded in this period.")
    else:
        out.append("| Date | Site | Severity /10 | Swelling | Type | Overnight | Resolved | Note |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in sorted(syms, key=lambda x: x["day"]):
            out.append(
                f"| {r['day']} | {r['injury_key']} | {r['severity'] if r['severity'] is not None else '—'} "
                f"| {'yes' if r['swelling'] else 'no'} | {r['pain_type'] or '—'} "
                f"| {'YES' if r['overnight'] else 'no'} | {r['resolved_by'] or '—'} "
                f"| {(r['note'] or '').replace('|', '/')} |"
            )

    events = [e for e in db.recent_events(s) if e["severity"] in ("warn", "alert")]
    if events:
        out.append("\n## Flagged events\n")
        for e in sorted(events, key=lambda x: x["day"]):
            out.append(f"- **{e['day']}** ({e['severity']}) {e['kind']}: {e['detail']}")

    out.append("\n## Prehab adherence\n")
    daily = db.daily_between(s, u)
    done = sum(1 for d in daily if d["prehab_done"])
    logged = sum(1 for d in daily if d["prehab_done"] is not None)
    out.append(f"Completed on {done} of {logged} logged days "
               f"({100 * done / logged:.0f}%) over {(until - since).days} days."
               if logged else "No prehab data logged.")
    out.append(f"\nProtocol: {', '.join(athlete.prehab_items)}")

    out.append("\n---\n*Generated by agoge. Objective metrics from a COROS Pace 3 "
               "with a chest heart-rate strap; symptom entries are self-reported "
               "and dated at time of entry.*")
    return "\n".join(out)


def write_physio_report(db: DB, athlete: Athlete, since: date,
                        until: date | None = None) -> Path:
    until = until or date.today()
    body = physio_report(db, athlete, since, until)
    out_dir = settings.data_dir / "exports"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"physio-{until.isoformat()}.md"
    path.write_text(body)
    return path
